#!/bin/bash

python HW87.py
cd libsvm-3.21
./svm-train -s 0 -t 1 -d 2 -g 1 -r 1 -c 0.0001 ../HW8train1all5CVtrain.txt HW8train1all5CVtrainc00001.txt.model
./svm-predict ../HW8train1all5CVtest.txt HW8train1all5CVtrainc00001.txt.model 1.txt


